Lattice Optimization
JuliaMolSim/GeometryOptimization.jl pull request #8
Opened 2024-02-19 13:42 UTC by CedricTravelletti

This PR implements lattice optimization, following the ASE implementation.

2024-03-09 14:47 UTC, CedricTravelletti commented on src/strain.jl
> +# TODO: deprecate.
Now removed.

2024-03-09 17:02 UTC, CedricTravelletti commented on src/optimization.jl
> +
Done. Added PR to DFTK and AtomsCalculators implementing the changes.

2024-05-21 22:35 UTC, cortner commented
what is the situation here? I was about to write an alternative geometry optimization wrapper porting the JuLIP implementation. But if this is ready or close to ready, then I will hold off.

2024-05-21 22:39 UTC, cortner requested changes
sorry, I meant to just leave a single comment. Just let me know in the conversation if this is on track or you need help or I should do something separate to meet my current requirements.

2024-05-21 22:39 UTC, cortner commented on src/strain.jl
> +function voigt_to_full(v)
I think you are messing with the types here, and also below in `full_to_voigt`. 

```
julia> function full_to_voigt(A)
           [A[1, 1], A[2, 2], A[3, 3], 2. * A[2, 3], 2. * A[1, 3], 2. * A[1, 2]]
       end
full_to_voigt (generic function with 1 method)

julia> 

julia> A = rand(Float32, 3,3)
3×3 Matrix{Float32}:
 0.934422  0.399876  0.339769
 0.241855  0.856102  0.199015
 0.573214  0.554009  0.683092

julia> full_to_voigt(A)
6-element Vector{Float64}:
 0.9344218969345093
 0.8561021089553833
 0.6830916404724121
 0.39803004264831543
 0.6795381307601929
 0.7997522354125977
```

2024-06-26 07:54 UTC, mfherbst commented
@CedricTravelletti Correct me if I'm wrong, but I believe the current state is that this is stalled until the Lux model state PR goes in (which should hopefully be very soon).

2025-01-01 11:22 UTC, mfherbst commented
Superseeded by #24.

2025-01-01 11:22 UTC, closed without merging